### PR TITLE
Adding "Nodebots - Javascript and robotics in the real world" book

### PR DESCRIPTION
**Pull request by willmendesneto**
Adding ["Nodebots - Javascript and robotic in the real world"](https://leanpub.com/nodebots-javascript-and-robotic-in-the-real-world) book information on the website book section.

Related to https://github.com/johnny-five-io/johnny-five.io/issues/107

### CODE REVIEW

**Comment by willmendesneto** [comment]
ping @rwaldron @reconbot

**Comment by rwaldron** [comment]
The one blocker is that someone needs to read it first 

@dtex @Resseguie @nodebotanist @nebrius @noopkat @Amorelandra @rockbot @deathbearbrown @lyzadanger @opheliasdaisies @ajfisher @monteslu 

If anyone has spare cycles to give this a read?

**Comment by nodebotanist** [comment]
I'll have some cycles this week and can give it a once-over

**Comment by willmendesneto** [comment]
@dtex @Resseguie @nodebotanist @nebrius @noopkat @Amorelandra @rockbot @deathbearbrown @lyzadanger @opheliasdaisies @ajfisher @monteslu @rwaldron Any updates or content I need to update?

**Comment by dtex** [comment]
Hi @willmendesneto I'll see if I can spend some time over the next couple of weeks (Holidays are the worst time for me). I did notice that there is a typo on the cover and some people might judge the book by that (even though your never supposed to judge a book by its cover :-P).

**Comment by willmendesneto** [comment]
I will update the cover image and, after that, I will update this PR. Thanks for the review @dtex.

**Comment by dtex** [comment]
@willmendesneto I was able to get about halfway through. Would you like feedback, or are you just looking for a green light on that link?

**Comment by willmendesneto** [comment]
@dtex The initial goal of this PR is to add a free content from the community on the website. However, feedback is always a gift and if you can give me some I really appreciate.

Do you have any other thoughts?

**Comment by rwaldron** [comment]
@dtex I'm looking for a team member to say "This is a good resource for our community"—so yeah, green light :)

**Comment by nodebotanist** [comment]
I'm adding to this thread because I said I'd follow up. I'm going to abstain from giving this the green light-- I won't argue if someone else does, but I cannot myself.

**Comment by willmendesneto** [comment]
Closing this Pull Request by lack of replies. Thanks folks

**Pull request closed without merging**
